In [1]:
# # 🌾 AgriIntel

# ## Agriculture Intelligence & Decision Support Platform

# ### Phase 1

# Data Understanding

# Author

# Aryan Dhiman

In [2]:
# Importing required libraries

import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display floating values with 2 decimal places
pd.options.display.float_format = "{:.2f}".format

In [3]:
# Loading all datasets

crop_df = pd.read_csv("../data/raw/crop_production.csv")

yield_df = pd.read_csv("../data/raw/crop_yield.csv")

weather_df = pd.read_csv("../data/raw/state_weather.csv")

soil_df = pd.read_csv("../data/raw/state_soil.csv")

In [4]:
# Display first five rows

crop_df.head()

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.00,Hectare,2061.00,Tonnes,1.64
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.00,Hectare,2083.00,Tonnes,1.66
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.00,Hectare,1525.00,Tonnes,1.21
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Arecanut,2001-02,Kharif,3100.00,Hectare,5239.00,Tonnes,1.69
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,Arecanut,2002-03,Whole Year,3105.00,Hectare,5267.00,Tonnes,1.70

In [5]:
yield_df.head()

,crop,year,season,state,area,production,fertilizer,pesticide,yield
0,Arecanut,1997,Whole Year,Assam,73814.00,56708,7024878.38,22882.34,0.80
1,Arhar/Tur,1997,Kharif,Assam,6637.00,4685,631643.29,2057.47,0.71
2,Castor seed,1997,Kharif,Assam,796.00,22,75755.32,246.76,0.24
3,Coconut,1997,Whole Year,Assam,19656.00,126905000,1870661.52,6093.36,5238.05
4,Cotton(lint),1997,Kharif,Assam,1739.00,794,165500.63,539.09,0.42

In [6]:
weather_df.head()

            state  year  avg_temp_c  total_rainfall_mm  avg_humidity_percent
0  Andhra Pradesh  1997       28.21            1191.08                 69.56
1  Andhra Pradesh  1998       28.21            1100.41                 71.95
2  Andhra Pradesh  1999       28.03             603.67                 66.91
3  Andhra Pradesh  2000       27.74            1070.25                 70.73
4  Andhra Pradesh  2001       28.08             910.13                 68.69

In [7]:
soil_df.head()

               state   N   P   K   pH
0     Andhra Pradesh  78  45  22 6.80
1  Arunachal Pradesh  55  15  35 5.50
2              Assam  60  18  38 5.80
3              Bihar  85  30  25 7.20
4       Chhattisgarh  70  35  20 6.50

In [8]:
# Dataset dimensions

print("Crop Dataset :", crop_df.shape)

print("Yield Dataset :", yield_df.shape)

print("Weather Dataset :", weather_df.shape)

print("Soil Dataset :", soil_df.shape)

Crop Dataset : (345407, 10)
Yield Dataset : (19689, 9)
Weather Dataset : (720, 5)
Soil Dataset : (30, 5)

In [9]:
# Dataset information

crop_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345407 entries, 0 to 345406
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             345407 non-null  object
 1   District          345407 non-null  object
 2   Crop              345375 non-null  object
 3   Year              345407 non-null  object
 4   Season            345406 non-null  object
 5   Area              345374 non-null  float64
 6   Area Units        345407 non-null  object
 7   Production        340414 non-null  float64
 8   Production Units  345407 non-null  object
 9   Yield             345374 non-null  float64
dtypes: float64(3), object(7)
memory usage: 26.4+ MB

In [10]:
crop_df.describe()

            Area    Production     Yield
count  345374.00     340414.00 345374.00
mean    11670.19     958371.15     79.41
std     45838.43   21529855.09    916.63
min         0.00          0.00      0.00
25%        74.00         87.00      0.55
50%       532.00        717.00      1.00
75%      4110.00       7176.00      2.47
max   8580100.00 1597800000.00  43958.33

In [20]:
crop_df.columns.tolist()

['State',
 'District',
 'Crop',
 'Year',
 'Season',
 'Area',
 'Area Units',
 'Production',
 'Production Units',
 'Yield']

In [12]:
crop_df.dtypes

State                object
District             object
Crop                 object
Year                 object
Season               object
Area                float64
Area Units           object
Production          float64
Production Units     object
Yield               float64
dtype: object

In [13]:
crop_df.isnull().sum()

State                  0
District               0
Crop                  32
Year                   0
Season                 1
Area                  33
Area Units             0
Production          4993
Production Units       0
Yield                 33
dtype: int64

In [14]:
crop_df.duplicated().sum()

np.int64(0)

In [15]:
crop_df.nunique()

State                   36
District               729
Crop                    56
Year                    24
Season                   6
Area                 48006
Area Units               1
Production           69078
Production Units         3
Yield               197154
dtype: int64

In [16]:
crop_df.sample(10)

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
176908,Andhra Pradesh,KURNOOL,Castor seed,2013-14,Rabi,42.00,Hectare,20.00,Tonnes,0.48
60805,Kerala,ALAPPUZHA,Cashewnut,2006-07,Whole Year,2995.00,Hectare,978.00,Tonnes,0.33
281359,Chhattisgarh,GAURELLA-PENDRA-MARWAHI,Banana,2019-20,Whole Year,1.00,Hectare,NaN,Tonnes,0.00
81603,Uttar Pradesh,CHANDAULI,Sugarcane,2005-06,Kharif,784.00,Hectare,34549.00,Tonnes,44.07
68383,Meghalaya,RI BHOI,Tapioca,2005-06,Whole Year,17.00,Hectare,84.00,Tonnes,4.94
40745,West Bengal,COOCHBEHAR,Ginger,2003-04,Kharif,400.00,Hectare,1000.00,Tonnes,2.50
61070,Kerala,THIRUVANANTHAPURAM,Rice,2005-06,Summer,14.00,Hectare,24.00,Tonnes,1.71
102512,Karnataka,BENGALURU URBAN,Moong(Green Gram),2008-09,Kharif,49.00,Hectare,7.00,Tonnes,0.14
248420,Madhya Pradesh,BETUL,Gram,2017-18,Rabi,41130.00,Hectare,61410.00,Tonnes,1.49
32933,Tamil Nadu,THOOTHUKUDI,Cotton(lint),2002-03,Kharif,7435.00,Hectare,3834.00,Bales,0.52

In [22]:
# Total number of unique states

crop_df["State"].nunique()

36

In [23]:
# Total Districts

crop_df["District"].nunique()

729

In [24]:
# Total Crops

crop_df["Crop"].nunique()

56

In [25]:
crop_df["Season"].value_counts()

Season
Kharif        138400
Rabi          100977
Whole Year     68689
Summer         22101
Winter          8250
Autumn          6989
Name: count, dtype: int64

In [27]:
crop_df["Year"].min(), crop_df["Year"].max()

('1997-98', '2020-21')

In [28]:
crop_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345407 entries, 0 to 345406
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             345407 non-null  object
 1   District          345407 non-null  object
 2   Crop              345375 non-null  object
 3   Year              345407 non-null  object
 4   Season            345406 non-null  object
 5   Area              345374 non-null  float64
 6   Area Units        345407 non-null  object
 7   Production        340414 non-null  float64
 8   Production Units  345407 non-null  object
 9   Yield             345374 non-null  float64
dtypes: float64(3), object(7)
memory usage: 26.4+ MB

In [29]:
yield_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   crop        19689 non-null  object
 1   year        19689 non-null  int64
 2   season      19689 non-null  object
 3   state       19689 non-null  object
 4   area        19689 non-null  float64
 5   production  19689 non-null  int64
 6   fertilizer  19689 non-null  float64
 7   pesticide   19689 non-null  float64
 8   yield       19689 non-null  float64
dtypes: float64(4), int64(2), object(3)
memory usage: 1.4+ MB

In [30]:
soil_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   30 non-null     object
 1   N       30 non-null     int64
 2   P       30 non-null     int64
 3   K       30 non-null     int64
 4   pH      30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB

In [31]:
crop_df.columns.tolist()

['State',
 'District',
 'Crop',
 'Year',
 'Season',
 'Area',
 'Area Units',
 'Production',
 'Production Units',
 'Yield']

In [32]:
yield_df.columns.tolist()

['crop',
 'year',
 'season',
 'state',
 'area',
 'production',
 'fertilizer',
 'pesticide',
 'yield']