In [1]:
# # 🌾 AgriIntel

# ## Agriculture Intelligence & Decision Support Platform

# ### Phase 2

# # Dataset Audit & Data Quality Assessment

# ---

# ## Objective

# The purpose of this notebook is to evaluate the quality of all datasets before preprocessing.

# This phase focuses on:

# - Dataset Profiling
# - Missing Values
# - Duplicate Records
# - Invalid Values
# - Category Validation
# - Numerical Validation
# - Data Consistency
# - Data Quality Report

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns",None)

In [3]:
# Loading all datasets

crop_df = pd.read_csv("../data/raw/crop_production.csv")

yield_df = pd.read_csv("../data/raw/crop_yield.csv")

weather_df = pd.read_csv("../data/raw/state_weather.csv")

soil_df = pd.read_csv("../data/raw/state_soil.csv")

In [4]:
print("="*60)
print("DATASET SHAPE")
print("="*60)

print(f"Crop Dataset : {crop_df.shape}")
print(f"Yield Dataset : {yield_df.shape}")
print(f"Weather Dataset : {weather_df.shape}")
print(f"Soil Dataset : {soil_df.shape}")

============================================================
DATASET SHAPE
============================================================
Crop Dataset : (345407, 10)
Yield Dataset : (19689, 9)
Weather Dataset : (720, 5)
Soil Dataset : (30, 5)

In [5]:
print("="*60)
print("MEMORY USAGE")
print("="*60)

print("Crop Dataset")

print(crop_df.memory_usage(deep=True).sum()/1024**2,"MB")

print()

print("Yield Dataset")

print(yield_df.memory_usage(deep=True).sum()/1024**2,"MB")

print()

print("Weather Dataset")

print(weather_df.memory_usage(deep=True).sum()/1024**2,"MB")

print()

print("Soil Dataset")

print(soil_df.memory_usage(deep=True).sum()/1024**2,"MB")

============================================================
MEMORY USAGE
============================================================
Crop Dataset
138.32018852233887 MB

Yield Dataset
4.211134910583496 MB

Weather Dataset
0.062084197998046875 MB

Soil Dataset
0.0027074813842773438 MB

In [6]:
print("="*60)
print("MISSING VALUES")
print("="*60)

crop_df.isnull().sum()

============================================================
MISSING VALUES
============================================================

State                  0
District               0
Crop                  32
Year                   0
Season                 1
Area                  33
Area Units             0
Production          4993
Production Units       0
Yield                 33
dtype: int64

In [7]:
print("="*60)
print("MISSING VALUES")
print("="*60)

yield_df.isnull().sum()

============================================================
MISSING VALUES
============================================================

crop          0
year          0
season        0
state         0
area          0
production    0
fertilizer    0
pesticide     0
yield         0
dtype: int64

In [8]:
print("="*60)
print("MISSING VALUES")
print("="*60)

weather_df.isnull().sum()

============================================================
MISSING VALUES
============================================================

state                   0
year                    0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
dtype: int64

In [10]:
print("="*60)
print("MISSING VALUES")
print("="*60)

soil_df.isnull().sum()

============================================================
MISSING VALUES
============================================================

state    0
N        0
P        0
K        0
pH       0
dtype: int64

In [11]:
round(crop_df.isnull().mean()*100,2)

State               0.00
District            0.00
Crop                0.01
Year                0.00
Season              0.00
Area                0.01
Area Units          0.00
Production          1.45
Production Units    0.00
Yield               0.01
dtype: float64

In [12]:
round(yield_df.isnull().mean()*100,2)

crop          0.0
year          0.0
season        0.0
state         0.0
area          0.0
production    0.0
fertilizer    0.0
pesticide     0.0
yield         0.0
dtype: float64

In [13]:
round(weather_df.isnull().mean()*100,2)

state                   0.0
year                    0.0
avg_temp_c              0.0
total_rainfall_mm       0.0
avg_humidity_percent    0.0
dtype: float64

In [14]:
round(soil_df.isnull().mean()*100,2)

state    0.0
N        0.0
P        0.0
K        0.0
pH       0.0
dtype: float64

In [15]:
print("="*60)

print("DUPLICATES")

print("="*60)

print(crop_df.duplicated().sum())

print(yield_df.duplicated().sum())

print(weather_df.duplicated().sum())

print(soil_df.duplicated().sum())

============================================================
DUPLICATES
============================================================
0
0
0
0

In [16]:
crop_df["State"].nunique()

36

In [17]:
crop_df["State"].value_counts()

State
Uttar Pradesh                  44781
Madhya Pradesh                 29906
Karnataka                      27493
Bihar                          24697
Rajasthan                      20363
Tamil Nadu                     18525
Assam                          18186
Maharashtra                    17922
Andhra Pradesh                 16363
Odisha                         16153
Chhattisgarh                   15285
Gujarat                        14053
West Bengal                    12596
Haryana                         8305
Uttarakhand                     6702
Nagaland                        5676
Himachal Pradesh                5043
Jharkhand                       5004
Kerala                          4870
Telangana                       4704
Jammu and Kashmir               4348
Arunachal Pradesh               4345
Meghalaya                       4322
Punjab                          4142
Manipur                         3120
Tripura                         2557
Mizoram                         2112
Puducherry                      1127
Sikkim                           876
Andaman and Nicobar Islands      728
Goa                              399
Dadra and Nagar Haveli           332
Delhi                            203
Chandigarh                       124
Daman and Diu                     44
Laddakh                            1
Name: count, dtype: int64

In [18]:
crop_df["District"].nunique()

729

In [19]:
crop_df["Crop"].nunique()

56

In [20]:
crop_df["Crop"].value_counts().head(20)

Crop
Rice                     21611
Maize                    20507
Moong(Green Gram)        15101
Urad                     14581
Sesamum                  13049
Groundnut                12586
Wheat                    11248
Rapeseed &Mustard        11034
Sugarcane                10942
Arhar/Tur                10895
Potato                   10756
Onion                    10675
Gram                     10474
Jowar                     9769
Dry chillies              8971
Bajra                     7796
Peas & beans (Pulses)     7266
Sunflower                 7244
Small millets             6985
Cotton(lint)              6475
Name: count, dtype: int64

In [21]:
crop_df["Season"].value_counts()

Season
Kharif        138400
Rabi          100977
Whole Year     68689
Summer         22101
Winter          8250
Autumn          6989
Name: count, dtype: int64

In [22]:
crop_df["Area Units"].value_counts()

Area Units
Hectare    345407
Name: count, dtype: int64

In [24]:
crop_df["Production Units"].value_counts()

Production Units
Tonnes    331686
Bales      10794
Nuts        2927
Name: count, dtype: int64

In [25]:
print(crop_df["Year"].min())

print(crop_df["Year"].max())

1997-98
2020-21

In [26]:
crop_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Area,345374.0,11670.191258,4.583843e+04,0.004,74.000000,532.0,4110.00000,8.580100e+06
Production,340414.0,958371.148664,2.152986e+07,0.000,87.000000,717.0,7176.00000,1.597800e+09
Yield,345374.0,79.407569,9.166287e+02,0.000,0.546742,1.0,2.46708,4.395833e+04

In [27]:
(crop_df["Area"]<0).sum()

np.int64(0)

In [28]:
(crop_df["Production"]<0).sum()

np.int64(0)

In [29]:
(crop_df["Yield"]<0).sum()

np.int64(0)

In [30]:
(crop_df["Production"]==0).sum()

np.int64(1024)

In [31]:
crop_df["State"].str.strip().str.title().equals(crop_df["State"])

False

In [32]:
crop_df["State"].str.contains("^ ").sum()

np.int64(0)

In [34]:
report = pd.DataFrame({

"Rows":[len(crop_df)],

"Columns":[crop_df.shape[1]],

"Missing Values":[crop_df.isnull().sum().sum()],

"Duplicate Rows":[crop_df.duplicated().sum()],

"Unique States":[crop_df["State"].nunique()],

"Unique Districts":[crop_df["District"].nunique()],

"Unique Crops":[crop_df["Crop"].nunique()]

})

report

,Rows,Columns,Missing Values,Duplicate Rows,Unique States,Unique Districts,Unique Crops
0,345407,10,5092,0,36,729,56

In [ ]:
# # Phase 2 Conclusion

# The datasets were successfully audited.

# Key findings:

# - Dataset dimensions recorded.

# - Missing values identified.

# - Duplicate records evaluated.

# - Data consistency checked.

# - Numerical validation completed.

# The datasets are now ready for preprocessing and cleaning.