In [1]:
# # 🌍 AgriIntel

# # Phase 9

# ## GIS & Interactive Maps

# ### Objective

# This notebook transforms agricultural data into interactive geographic visualizations.

# Using Plotly, we will build interactive maps to analyze:

# - Production
# - Yield
# - Area
# - Weather
# - Soil
# - Crop Distribution

# These maps provide geographical intelligence for decision support.

In [2]:
# ============================================================
# AgriIntel
#
# Phase 9
#
# GIS & Interactive Maps
# ============================================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns",None)

In [3]:
master = pd.read_csv("../data/final/master_dataset_featured.csv")

print(master.shape)

master.head()

(345374, 40)

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield,Start_Year,Year_yield,Area_yield,Production_yield,fertilizer,pesticide,Yield_yield,Year_weather,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH,End_Year,Decade,Year_Group,Rainfall_Category,Temperature_Category,Humidity_Category,Production_per_Hectare,Fertilizer_per_Hectare,Pesticide_per_Hectare,Rainfall_per_Hectare,Crop_Category,Production_Level,Yield_Level,Weather_Data_Available,Soil_Data_Available
0,Andaman And Nicobar Islands,Nicobars,Arecanut,2001-02,Kharif,1254.0,Hectare,2061.0,Tonnes,1.643541,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002,2000,2001-2005,NaN,NaN,NaN,1.643541,NaN,NaN,NaN,Other,Medium,Medium,False,False
1,Andaman And Nicobar Islands,Nicobars,Arecanut,2002-03,Whole Year,1258.0,Hectare,2083.0,Tonnes,1.655803,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003,2000,2001-2005,NaN,NaN,NaN,1.655803,NaN,NaN,NaN,Other,Medium,Medium,False,False
2,Andaman And Nicobar Islands,Nicobars,Arecanut,2003-04,Whole Year,1261.0,Hectare,1525.0,Tonnes,1.209358,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,2000,2001-2005,NaN,NaN,NaN,1.209358,NaN,NaN,NaN,Other,Medium,Medium,False,False
3,Andaman And Nicobar Islands,North And Middle Andaman,Arecanut,2001-02,Kharif,3100.0,Hectare,5239.0,Tonnes,1.690000,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002,2000,2001-2005,NaN,NaN,NaN,1.690000,NaN,NaN,NaN,Other,High,Medium,False,False
4,Andaman And Nicobar Islands,South Andamans,Arecanut,2002-03,Whole Year,3105.0,Hectare,5267.0,Tonnes,1.696296,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003,2000,2001-2005,NaN,NaN,NaN,1.696296,NaN,NaN,NaN,Other,High,Medium,False,False

In [4]:
# Missing values represent unavailable observations in the source datasets and have been intentionally preserved to maintain data integrity.

In [5]:
print("="*70)

print("GIS DATASET OVERVIEW")

print("="*70)

print()

print(master.shape)

print()

master.info()

======================================================================
GIS DATASET OVERVIEW
======================================================================

(345374, 40)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345374 entries, 0 to 345373
Data columns (total 40 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   State                   345374 non-null  object
 1   District                345374 non-null  object
 2   Crop                    345374 non-null  object
 3   Year                    345374 non-null  object
 4   Season                  345374 non-null  object
 5   Area                    345374 non-null  float64
 6   Area Units              345374 non-null  object
 7   Production              340414 non-null  float64
 8   Production Units        345374 non-null  object
 9   Yield                   345374 non-null  float64
 10  Start_Year              345374 non-null  int64
 11  Year_yield              318023 non-null  float64
 12  Area_yield              318023 non-null  float64
 13  Production_yield        318023 non-null  float64
 14  fertilizer              318023 non-null  float64
 15  pesticide               318023 non-null  float64
 16  Yield_yield             318023 non-null  float64
 17  Year_weather            323787 non-null  float64
 18  avg_temp_c              323787 non-null  float64
 19  total_rainfall_mm       323787 non-null  float64
 20  avg_humidity_percent    323787 non-null  float64
 21  N                       323787 non-null  float64
 22  P                       323787 non-null  float64
 23  K                       323787 non-null  float64
 24  pH                      323787 non-null  float64
 25  End_Year                345374 non-null  int64
 26  Decade                  345374 non-null  int64
 27  Year_Group              345374 non-null  object
 28  Rainfall_Category       323485 non-null  object
 29  Temperature_Category    323787 non-null  object
 30  Humidity_Category       323787 non-null  object
 31  Production_per_Hectare  340414 non-null  float64
 32  Fertilizer_per_Hectare  318023 non-null  float64
 33  Pesticide_per_Hectare   318023 non-null  float64
 34  Rainfall_per_Hectare    323787 non-null  float64
 35  Crop_Category           345374 non-null  object
 36  Production_Level        340414 non-null  object
 37  Yield_Level             345374 non-null  object
 38  Weather_Data_Available  345374 non-null  bool
 39  Soil_Data_Available     345374 non-null  bool
dtypes: bool(2), float64(21), int64(3), object(14)
memory usage: 100.8+ MB

In [6]:
state_summary = (

    master

    .groupby("State")

    .agg({

        "Production":"sum",

        "Yield":"mean",

        "Area":"sum",

        "avg_temp_c":"mean",

        "total_rainfall_mm":"mean",

        "avg_humidity_percent":"mean"

    })

    .reset_index()

)

state_summary.head()

,State,Production,Yield,Area,avg_temp_c,total_rainfall_mm,avg_humidity_percent
0,Andaman And Nicobar Islands,2.053355e+09,324.287494,8.405980e+05,NaN,NaN,NaN
1,Andhra Pradesh,2.607622e+10,212.827867,2.389253e+08,28.009992,1000.394584,69.700908
2,Arunachal Pradesh,9.522010e+06,3.332913,5.725531e+06,22.364506,2202.294371,76.471853
3,Assam,3.637715e+09,228.754561,7.734260e+07,22.941121,1934.523800,76.529176
4,Bihar,5.449535e+08,3.780652,1.679954e+08,26.193180,1001.112327,55.628033

In [7]:
print(state_summary.shape)

state_summary.describe()

(36, 7)

,Production,Yield,Area,avg_temp_c,total_rainfall_mm,avg_humidity_percent
count,3.600000e+01,36.000000,3.600000e+01,30.000000,30.000000,30.000000
mean,9.062304e+09,93.317792,1.119606e+08,23.417652,1406.487762,64.866401
std,2.663699e+10,178.147219,1.592751e+08,5.038459,598.557097,11.923865
min,1.092000e+02,0.400000,2.730000e+02,7.412900,704.827914,44.556847
25%,1.684320e+07,3.276577,2.503025e+06,22.503257,1002.922613,54.812416
50%,1.868886e+08,4.746262,2.645371e+07,25.275689,1236.765726,68.851861
75%,1.922262e+09,56.228957,1.635290e+08,26.408289,1731.037294,74.854967
max,1.297006e+11,779.961428,5.426726e+08,28.066060,3000.934891,81.602348

In [8]:
state_summary = (

    state_summary

    .sort_values(

        "Production",

        ascending=False

    )

)

state_summary.head(10)

,State,Production,Yield,Area,avg_temp_c,total_rainfall_mm,avg_humidity_percent
17,Kerala,1.297006e+11,422.329994,3.639106e+07,26.896618,1786.631916,80.170113
30,Tamil Nadu,7.805176e+10,303.255555,1.103739e+08,27.963597,1208.764076,72.163242
16,Karnataka,6.377280e+10,157.478676,2.579074e+08,23.695007,849.571492,68.002814
1,Andhra Pradesh,2.607622e+10,212.827867,2.389253e+08,28.009992,1000.394584,69.700908
35,West Bengal,8.941179e+09,430.561452,2.376823e+08,25.815758,1564.253429,73.770433
33,Uttar Pradesh,4.442585e+09,5.620901,5.426726e+08,25.921372,1009.319856,51.383362
3,Assam,3.637715e+09,228.754561,7.734260e+07,22.941121,1934.523800,76.529176
10,Goa,2.194004e+09,362.442833,2.750900e+06,27.405288,2169.956466,73.661905
0,Andaman And Nicobar Islands,2.053355e+09,324.287494,8.405980e+05,NaN,NaN,NaN
20,Maharashtra,1.878565e+09,3.819867,4.619396e+08,26.711377,2404.032075,67.338738

In [10]:
fig = px.choropleth(

    state_summary,

    locations="State",

    locationmode="India states",

    color="Production",

    hover_name="State",

    hover_data={

        "Yield":":.2f",

        "Area":":.2f",

        "avg_temp_c":":.2f",

        "total_rainfall_mm":":.2f",

        "avg_humidity_percent":":.2f"

    },

    scope="asia",

    color_continuous_scale="Viridis",

    title="India State-wise Agricultural Production"

)

fig.update_geos(

    fitbounds="locations",

    visible=False

)

fig.update_layout(

    title_x=.5,

    height=700

)

fig.show()

ValueError:
    Invalid value of type 'builtins.str' received for the 'locationmode' property of choropleth
        Received value: 'India states'

    The 'locationmode' property is an enumeration that may be specified as:
      - One of the following enumeration values:
            ['ISO-3', 'USA-states', 'country names', 'geojson-id']